config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'profiles#index'
  get 'profiles/download', to: 'profiles#resume'
  get 'profiles/videos', to: 'profiles#videos'
  get '/blogs/recent', to: 'blog_page#recent'
  get '/blogs/technology', to: 'blog_page#technology'
  get '/blogs/programming', to: 'blog_page#programming'
  get '/blogs/music', to: 'blog_page#music'
  get '/blogs/travelling', to: 'blog_page#travelling'
  get '/blogs/bikes', to: 'blog_page#bikes'
  resources :blogs, only: [:new, :create, :show]

end

app/views/shared/_blog_intro.html.erb
<div class="banner technology">
  <div class="greyimage">
    <%= content_tag(:h1, title) %>
    <h3>Every once in a while, a new technology, an old problem, and a big idea turn into an innovation.</h3>
    <div class="wrapper">
      <%= link_to 'Write a blog', 'new' %>
    </div>
  </div>
</div>

app/views/shared/_blog_list.html.erb
<div class="blog_list_main">
  <% blogs.each do |blog| %>
      <%=link_to blog.title, blog_path(blog.id), class: 'h1' %>
      <div class="myclass">
        <p><%= ActionView::Base.full_sanitizer.sanitize(blog.description) %></p>
      </div>
      <%=link_to 'Read More', blog_path(blog.id) %>
      <span class="posted_tag"><%= "Posted on #{blog.created_at}" %></span>
      <hr />
  <% end %>
</div>

app/views/shared/_blog_nav.html.erb
<div class="back-nav-container">
  <div class="back-button">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <%= link_to("Aj's profile", :root) %>
  </div>
    <nav class="navbar navbar-default navbar-inverse" role="navigation">
      <div class="container-fluid" id="navfluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigationbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <div class="collapse navbar-collapse" id="navigationbar">
          <ul class="nav navbar-nav">
            <% @blog_titles.each do |blog_title| %>
                <% blog_link = "/blogs/#{blog_title.name.downcase}" %>
                <li><a href= <%= blog_link %>><%= blog_title.name %></a></li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b>Login</b> <span class="caret"></span></a>
              <ul id="login-dp" class="dropdown-menu">
              <li>
              <div class="row">
              <div class="col-md-12">
              Login via
              <div class="social-buttons">
              <a href="#" class="btn btn-fb"><i class="fa fa-facebook"></i> Facebook</a>
              <a href="#" class="btn btn-tw"><i class="fa fa-twitter"></i> Twitter</a>
              </div>
              or
              <form class="form" role="form" method="post" action="login" accept-charset="UTF-8" id="login-nav">
              <div class="form-group">
              <label class="sr-only" for="exampleInputEmail2">Email address</label>
              <input type="email" class="form-control" id="exampleInputEmail2" placeholder="Email address" required>
              </div>
              <div class="form-group">
              <label class="sr-only" for="exampleInputPassword2">Password</label>
              <input type="password" class="form-control" id="exampleInputPassword2" placeholder="Password" required>
              <div class="help-block text-right"><a href="">Forget the password ?</a></div>
              </div>
              <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block">Sign in</button>
              </div>
              <div class="checkbox">
              <label>
              <input type="checkbox"> keep me logged-in
              </label>
              </div>
              </form>
              </div>
              <div class="bottom text-center">
              New here ? <a href='/users/sign_up'><b>Join Us</b></a>
              </div>
              </div>
              </li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->
    </nav>
</div>